# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a826ed6c27794c1689656c474abcda8b67d2b1c5f546ad88777683ef3faf45d9f1a7f8b5fe8a1941536b2f5123c8748a5a23e7c1588bacd2d69189d7a96663b

test:
  secret_key_base: 7c313296b232f5a9ddbd166867541d5af9d98ed7a99e3a6124fc3dd46bad1a659d69fcb75eadaaf907dc429acfd62b15c66124255d171ce9ae7d10add5386231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
